# Colors (Apple System Colors Light)

[colors.bright]
black = '#464646'
blue = '#0a84ff'
cyan = '#69c9f2'
green = '#32d74b'
magenta = '#bf5af2'
red = '#ff453a'
white = '#ffffff'
yellow = '#e5bc00'

[colors.cursor]
cursor = '#98989d'
text = '#ffffff'

[colors.normal]
black = '#1a1a1a'
blue = '#0869cb'
cyan = '#479ec2'
green = '#26a439'
magenta = '#9647bf'
red = '#cc372e'
white = '#98989d'
yellow = '#cdac08'

[colors.primary]
background = '#feffff'
foreground = '#000000'

[colors.selection]
background = '#abd8ff'
text = '#000000'
