# Colors (Ayu)

[colors.bright]
black = '#686868'
blue = '#59c2ff'
cyan = '#95e6cb'
green = '#aad94c'
magenta = '#d2a6ff'
red = '#f07178'
white = '#ffffff'
yellow = '#ffb454'

[colors.cursor]
cursor = '#e6b450'
text = '#0b0e14'

[colors.normal]
black = '#11151c'
blue = '#53bdfa'
cyan = '#90e1c6'
green = '#7fd962'
magenta = '#cda1fa'
red = '#ea6c73'
white = '#c7c7c7'
yellow = '#f9af4f'

[colors.primary]
background = '#0b0e14'
foreground = '#bfbdb6'

[colors.selection]
background = '#409fff'
text = '#0b0e14'
