# Colors (Builtin Pastel Dark)

[colors.bright]
black = '#7c7c7c'
blue = '#b5dcff'
cyan = '#dfdffe'
green = '#ceffac'
magenta = '#ff9cfe'
red = '#ffb6b0'
white = '#ffffff'
yellow = '#ffffcc'

[colors.cursor]
cursor = '#ffa560'
text = '#ffffff'

[colors.normal]
black = '#4f4f4f'
blue = '#96cbfe'
cyan = '#c6c5fe'
green = '#a8ff60'
magenta = '#ff73fd'
red = '#ff6c60'
white = '#eeeeee'
yellow = '#ffffb6'

[colors.primary]
background = '#000000'
foreground = '#bbbbbb'

[colors.selection]
background = '#363983'
text = '#f2f2f2'
