# Colors (catppuccin-mocha)

[colors.bright]
black = '#585b70'
blue = '#89b4fa'
cyan = '#94e2d5'
green = '#a6e3a1'
magenta = '#f5c2e7'
red = '#f38ba8'
white = '#a6adc8'
yellow = '#f9e2af'

[colors.cursor]
cursor = '#f5e0dc'
text = '#cdd6f4'

[colors.normal]
black = '#45475a'
blue = '#89b4fa'
cyan = '#94e2d5'
green = '#a6e3a1'
magenta = '#f5c2e7'
red = '#f38ba8'
white = '#bac2de'
yellow = '#f9e2af'

[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
background = '#585b70'
text = '#cdd6f4'
