# Colors (ChallengerDeep)

[colors.bright]
black = '#565575'
blue = '#91ddff'
cyan = '#aaffe4'
green = '#95ffa4'
magenta = '#c991e1'
red = '#ff8080'
white = '#cbe3e7'
yellow = '#ffe9aa'

[colors.cursor]
cursor = '#fbfcfc'
text = '#ff271d'

[colors.normal]
black = '#141228'
blue = '#65b2ff'
cyan = '#63f2f1'
green = '#62d196'
magenta = '#906cff'
red = '#ff5458'
white = '#a6b3cc'
yellow = '#ffb378'

[colors.primary]
background = '#1e1c31'
foreground = '#cbe1e7'

[colors.selection]
background = '#cbe1e7'
text = '#1e1c31'
