# Colors (Cobalt Next Dark)

[colors.bright]
black = '#62747f'
blue = '#7ac0eb'
cyan = '#84e4e3'
green = '#baddbb'
magenta = '#f3ccef'
red = '#e47e8b'
white = '#ffffff'
yellow = '#ffdc91'

[colors.cursor]
cursor = '#ffc64c'
text = '#ffffff'

[colors.normal]
black = '#262f37'
blue = '#409dd4'
cyan = '#37b5b4'
green = '#8cc98f'
magenta = '#cba3c7'
red = '#f94967'
white = '#d7deea'
yellow = '#ffc64c'

[colors.primary]
background = '#0b1c24'
foreground = '#d7deea'

[colors.selection]
background = '#37b5b4'
text = '#ffffff'
