# Colors (Electron Highlighter)

[colors.bright]
black = '#4a6789'
blue = '#77abff'
cyan = '#00fdff'
green = '#00ffc3'
magenta = '#daa4f4'
red = '#ff6c8d'
white = '#c3cee2'
yellow = '#ffd7a9'

[colors.cursor]
cursor = '#a5b6d4'
text = '#1a1b27'

[colors.normal]
black = '#15161f'
blue = '#77abff'
cyan = '#00fdff'
green = '#00ffc3'
magenta = '#daa4f4'
red = '#ff6c8d'
white = '#778faf'
yellow = '#ffd7a9'

[colors.primary]
background = '#23283d'
foreground = '#a5b6d4'

[colors.selection]
background = '#25345a'
text = '#a5b6d4'
