# Colors (Everforest Dark - Hard)

[colors.bright]
black = '#a6b0a0'
blue = '#3a94c5'
cyan = '#35a77c'
green = '#8da101'
magenta = '#df69ba'
red = '#f85552'
white = '#fffbef'
yellow = '#dfa000'

[colors.cursor]
cursor = '#e69875'
text = '#4c3743'

[colors.normal]
black = '#7a8478'
blue = '#7fbbb3'
cyan = '#83c092'
green = '#a7c080'
magenta = '#d699b6'
red = '#e67e80'
white = '#f2efdf'
yellow = '#dbbc7f'

[colors.primary]
background = '#1e2326'
foreground = '#d3c6aa'

[colors.selection]
background = '#4c3743'
text = '#d3c6aa'
