# Colors (farmhouse-dark)

[colors.bright]
black = '#394047'
blue = '#006efe'
cyan = '#19e062'
green = '#7ac100'
magenta = '#bf3b7f'
red = '#eb0009'
white = '#f4eef0'
yellow = '#ea9a00'

[colors.cursor]
cursor = '#006efe'
text = '#e8e4e1'

[colors.normal]
black = '#1d2027'
blue = '#0049e6'
cyan = '#1fb65c'
green = '#549d00'
magenta = '#9f1b61'
red = '#ba0004'
white = '#e8e4e1'
yellow = '#c87300'

[colors.primary]
background = '#1d2027'
foreground = '#e8e4e1'

[colors.selection]
background = '#4d5658'
text = '#b3b1aa'
