# Colors (Github)

[colors.bright]
black = '#666666'
blue = '#2e6cba'
cyan = '#1cfafe'
green = '#87d5a2'
magenta = '#ffa29f'
red = '#de0000'
white = '#ffffff'
yellow = '#f1d007'

[colors.cursor]
cursor = '#3f3f3f'
text = '#f4f4f4'

[colors.normal]
black = '#3e3e3e'
blue = '#003e8a'
cyan = '#89d1ec'
green = '#07962a'
magenta = '#e94691'
red = '#970b16'
white = '#ffffff'
yellow = '#f8eec7'

[colors.primary]
background = '#f4f4f4'
foreground = '#3e3e3e'

[colors.selection]
background = '#a9c1e2'
text = '#535353'
