# Colors (Gruber Darker)

[colors.bright]
black = '#54494e'
blue = '#92a7cb'
cyan = '#90aa9e'
green = '#42dc00'
magenta = '#afafda'
red = '#ff3851'
white = '#f5f5f5'
yellow = '#ffdb00'

[colors.cursor]
cursor = '#ffdb00'
text = '#ffffff'

[colors.normal]
black = '#181818'
blue = '#92a7cb'
cyan = '#90aa9e'
green = '#42dc00'
magenta = '#a095cb'
red = '#ff0a36'
white = '#e4e4e4'
yellow = '#ffdb00'

[colors.primary]
background = '#181818'
foreground = '#e4e4e4'

[colors.selection]
background = '#ffffff'
text = '#54494e'
