# Colors (Gruvbox Light Hard)

[colors.bright]
black = '#928374'
blue = '#076678'
cyan = '#427b58'
green = '#79740e'
magenta = '#8f3f71'
red = '#9d0006'
white = '#3c3836'
yellow = '#b57614'

[colors.cursor]
cursor = '#3c3836'
text = '#f9f5d7'

[colors.normal]
black = '#f9f5d7'
blue = '#458588'
cyan = '#689d6a'
green = '#98971a'
magenta = '#b16286'
red = '#cc241d'
white = '#7c6f64'
yellow = '#d79921'

[colors.primary]
background = '#f9f5d7'
foreground = '#3c3836'

[colors.selection]
background = '#3c3836'
text = '#f9f5d7'
