# Colors (GruvboxLightHard)

[colors.bright]
black = '#9d8374'
blue = '#458588'
cyan = '#689d69'
green = '#98971a'
magenta = '#b16186'
red = '#cc241d'
white = '#7c6f64'
yellow = '#d79921'

[colors.cursor]
cursor = '#282828'
text = '#f8f4d6'

[colors.normal]
black = '#f8f4d6'
blue = '#076678'
cyan = '#427b58'
green = '#79740e'
magenta = '#8f3f71'
red = '#9d0006'
white = '#3c3836'
yellow = '#b57614'

[colors.primary]
background = '#f8f4d6'
foreground = '#282828'

[colors.selection]
background = '#d5c4a1'
text = '#665c54'
