# Colors (Gruvbox Material Dark)

[colors.bright]
black = '#7c6f64'
blue = '#7daea3'
cyan = '#89b482'
green = '#a9b665'
magenta = '#d3869b'
red = '#ea6962'
white = '#ddc7a1'
yellow = '#d8a657'

[colors.cursor]
cursor = '#d4be98'
text = '#a18b65'

[colors.normal]
black = '#282828'
blue = '#7daea3'
cyan = '#89b482'
green = '#a9b665'
magenta = '#d3869b'
red = '#ea6962'
white = '#d4be98'
yellow = '#d8a657'

[colors.primary]
background = '#282828'
foreground = '#d4be98'

[colors.selection]
background = '#d4be98'
text = '#282828'
