# Colors (Havn Skumring)

[colors.bright]
black = '#36425e'
blue = '#5186cb'
cyan = '#d17ab6'
green = '#8c9e8f'
magenta = '#9b7cee'
red = '#d17264'
white = '#fff6e1'
yellow = '#eac58c'

[colors.cursor]
cursor = '#277a6f'
text = '#e0e4f3'

[colors.normal]
black = '#252c47'
blue = '#596cf7'
cyan = '#d588c1'
green = '#6ead7b'
magenta = '#7c719e'
red = '#ea563e'
white = '#dce0ee'
yellow = '#f8b330'

[colors.primary]
background = '#111522'
foreground = '#d6dbeb'

[colors.selection]
background = '#2b514b'
text = '#dce0ef'
