# Colors (iTerm2 Tango Light)

[colors.bright]
black = '#686a66'
blue = '#84b0d8'
cyan = '#37e6e8'
green = '#99e343'
magenta = '#bc94b7'
red = '#f54235'
white = '#f1f1f0'
yellow = '#fdeb61'

[colors.cursor]
cursor = '#000000'
text = '#ffffff'

[colors.normal]
black = '#000000'
blue = '#427ab3'
cyan = '#00a7aa'
green = '#5ea702'
magenta = '#89658e'
red = '#d81e00'
white = '#dbded8'
yellow = '#cfae00'

[colors.primary]
background = '#ffffff'
foreground = '#000000'

[colors.selection]
background = '#c1deff'
text = '#000000'
