# Colors (Kanagawa Lotus)

[colors.bright]
black = '#8a8980'
blue = '#6693bf'
cyan = '#5e857a'
green = '#6e915f'
magenta = '#624c83'
red = '#d7474b'
white = '#43436c'
yellow = '#836f4a'

[colors.cursor]
cursor = '#43436c'
text = '#f2ecbc'

[colors.normal]
black = '#1f1f28'
blue = '#4d699b'
cyan = '#597b75'
green = '#6f894e'
magenta = '#b35b79'
red = '#c84053'
white = '#545464'
yellow = '#77713f'

[colors.primary]
background = '#f2ecbc'
foreground = '#545464'

[colors.selection]
background = '#545464'
text = '#f2ecbc'
