# Colors (Kanso Zen)

[colors.bright]
black = '#a4a7a4'
blue = '#7fb4ca'
cyan = '#7aa89f'
green = '#87a987'
magenta = '#938aa9'
red = '#e46876'
white = '#c5c9c7'
yellow = '#e6c384'

[colors.cursor]
cursor = '#c5c9c7'
text = '#090e13'

[colors.normal]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#c8c093'
yellow = '#c4b28a'

[colors.primary]
background = '#090e13'
foreground = '#c5c9c7'

[colors.selection]
background = '#393b44'
text = '#c5c9c7'
