# Colors (Kurokula)

[colors.bright]
black = '#515151'
blue = '#90dbff'
cyan = '#ffcdb6'
green = '#afffa5'
magenta = '#ad93ff'
red = '#ffc34c'
white = '#ffffff'
yellow = '#fff700'

[colors.cursor]
cursor = '#7a1c1c'
text = '#fffbf2'

[colors.normal]
black = '#333333'
blue = '#5c91dd'
cyan = '#867268'
green = '#78b3a9'
magenta = '#8b79a6'
red = '#c35a52'
white = '#e0cfc2'
yellow = '#e1b917'

[colors.primary]
background = '#141515'
foreground = '#e0cfc2'

[colors.selection]
background = '#515151'
text = '#ffc34c'
