# Colors (LiquidCarbonTransparentInverse)

[colors.bright]
black = '#ffffff'
blue = '#0099cc'
cyan = '#7ac4cc'
green = '#559a70'
magenta = '#cc69c8'
red = '#ff3030'
white = '#000000'
yellow = '#ccac00'

[colors.cursor]
cursor = '#ffffff'
text = '#000000'

[colors.normal]
black = '#bccccd'
blue = '#0099cc'
cyan = '#7ac4cc'
green = '#559a70'
magenta = '#cc69c8'
red = '#ff3030'
white = '#000000'
yellow = '#ccac00'

[colors.primary]
background = '#000000'
foreground = '#afc2c2'

[colors.selection]
background = '#7dbeff'
text = '#000000'
