# Colors (midnight-in-mojave)

[colors.bright]
black = '#1e1e1e'
blue = '#0a84ff'
cyan = '#5ac8fa'
green = '#32d74b'
magenta = '#bf5af2'
red = '#ff453a'
white = '#ffffff'
yellow = '#ffd60a'

[colors.cursor]
cursor = '#32d74b'
text = '#1c1c1c'

[colors.normal]
black = '#1e1e1e'
blue = '#0a84ff'
cyan = '#5ac8fa'
green = '#32d74b'
magenta = '#bf5af2'
red = '#ff453a'
white = '#ffffff'
yellow = '#ffd60a'

[colors.primary]
background = '#1e1e1e'
foreground = '#ffffff'

[colors.selection]
background = '#4a504d'
text = '#ffffff'
