# Colors (Modus Vivendi)

[colors.bright]
black = '#595959'
blue = '#79a8ff'
cyan = '#6ae4b9'
green = '#00c06f'
magenta = '#b6a0ff'
red = '#ff7f9f'
white = '#ffffff'
yellow = '#fec43f'

[colors.cursor]
cursor = '#ffffff'
text = '#000000'

[colors.normal]
black = '#000000'
blue = '#2fafff'
cyan = '#00d3d0'
green = '#44bc44'
magenta = '#feacd0'
red = '#ff5f59'
white = '#a6a6a6'
yellow = '#d0bc00'

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.selection]
background = '#5a5a5a'
text = '#ffffff'
