# Colors (Monokai Remastered)

[colors.bright]
black = '#625e4c'
blue = '#9d65ff'
cyan = '#58d1eb'
green = '#98e024'
magenta = '#f4005f'
red = '#f4005f'
white = '#f6f6ef'
yellow = '#e0d561'

[colors.cursor]
cursor = '#fc971f'
text = '#000000'

[colors.normal]
black = '#1a1a1a'
blue = '#9d65ff'
cyan = '#58d1eb'
green = '#98e024'
magenta = '#f4005f'
red = '#f4005f'
white = '#c4c5b5'
yellow = '#fd971f'

[colors.primary]
background = '#0c0c0c'
foreground = '#d9d9d9'

[colors.selection]
background = '#343434'
text = '#ffffff'
