# Colors (neobones_light)

[colors.bright]
black = '#b3c6b6'
blue = '#1d5573'
cyan = '#2b747c'
green = '#3f5a22'
magenta = '#7b3b70'
red = '#94253e'
white = '#415934'
yellow = '#803d1c'

[colors.cursor]
cursor = '#202e18'
text = '#e5ede6'

[colors.normal]
black = '#e5ede6'
blue = '#286486'
cyan = '#3b8992'
green = '#567a30'
magenta = '#88507d'
red = '#a8334c'
white = '#202e18'
yellow = '#944927'

[colors.primary]
background = '#e5ede6'
foreground = '#202e18'

[colors.selection]
background = '#ade48c'
text = '#202e18'
