# Colors (One Double Dark)

[colors.bright]
black = '#525d6f'
blue = '#6dcaff'
cyan = '#00e5fb'
green = '#82d882'
magenta = '#ff7bf4'
red = '#ff777b'
white = '#f7f9fc'
yellow = '#f5c065'

[colors.cursor]
cursor = '#f5e0dc'
text = '#9aa3c1'

[colors.normal]
black = '#3d4452'
blue = '#3fb1f5'
cyan = '#17b9c4'
green = '#8cc570'
magenta = '#d373e3'
red = '#f16372'
white = '#dbdfe5'
yellow = '#ecbe70'

[colors.primary]
background = '#282c34'
foreground = '#dbdfe5'

[colors.selection]
background = '#585b70'
text = '#cdd6f4'
