# Colors (OneHalfLight)

[colors.bright]
black = '#4f525e'
blue = '#61afef'
cyan = '#56b6c2'
green = '#98c379'
magenta = '#c678dd'
red = '#e06c75'
white = '#ffffff'
yellow = '#e5c07b'

[colors.cursor]
cursor = '#bfceff'
text = '#383a42'

[colors.normal]
black = '#383a42'
blue = '#0184bc'
cyan = '#0997b3'
green = '#50a14f'
magenta = '#a626a4'
red = '#e45649'
white = '#fafafa'
yellow = '#c18401'

[colors.primary]
background = '#fafafa'
foreground = '#383a42'

[colors.selection]
background = '#bfceff'
text = '#383a42'
