# Colors (PencilDark)

[colors.bright]
black = '#424242'
blue = '#20bbfc'
cyan = '#4fb8cc'
green = '#5fd7af'
magenta = '#6855de'
red = '#fb007a'
white = '#f1f1f1'
yellow = '#f3e430'

[colors.cursor]
cursor = '#20bbfc'
text = '#f1f1f1'

[colors.normal]
black = '#212121'
blue = '#008ec4'
cyan = '#20a5ba'
green = '#10a778'
magenta = '#523c79'
red = '#c30771'
white = '#d9d9d9'
yellow = '#a89c14'

[colors.primary]
background = '#212121'
foreground = '#f1f1f1'

[colors.selection]
background = '#b6d6fd'
text = '#f1f1f1'
