# Colors (rose-pine-moon)

[colors.bright]
black = '#6e6a86'
blue = '#3e8fb0'
cyan = '#ea9a97'
green = '#9ccfd8'
magenta = '#c4a7e7'
red = '#eb6f92'
white = '#e0def4'
yellow = '#f6c177'

[colors.cursor]
cursor = '#e0def4'
text = '#232136'

[colors.normal]
black = '#393552'
blue = '#3e8fb0'
cyan = '#ea9a97'
green = '#9ccfd8'
magenta = '#c4a7e7'
red = '#eb6f92'
white = '#e0def4'
yellow = '#f6c177'

[colors.primary]
background = '#232136'
foreground = '#e0def4'

[colors.selection]
background = '#232136'
text = '#e0def4'
