# Colors (Seafoam Pastel)

[colors.bright]
black = '#8a8a8a'
blue = '#7ac3cf'
cyan = '#ade0e0'
green = '#98d9aa'
magenta = '#d6b2a1'
red = '#cf937a'
white = '#e0e0e0'
yellow = '#fae79d'

[colors.cursor]
cursor = '#57647a'
text = '#323232'

[colors.normal]
black = '#757575'
blue = '#4d7b82'
cyan = '#729494'
green = '#728c62'
magenta = '#8a7267'
red = '#825d4d'
white = '#e0e0e0'
yellow = '#ada16d'

[colors.primary]
background = '#243435'
foreground = '#d4e7d4'

[colors.selection]
background = '#ffffff'
text = '#9e8b13'
