# Colors (Smyck)

[colors.bright]
black = '#7a7a7a'
blue = '#8dcff0'
cyan = '#6ad9cf'
green = '#c4f137'
magenta = '#f79aff'
red = '#d6837c'
white = '#f7f7f7'
yellow = '#fee14d'

[colors.cursor]
cursor = '#bbbbbb'
text = '#ffffff'

[colors.normal]
black = '#000000'
blue = '#62a3c4'
cyan = '#207383'
green = '#7da900'
magenta = '#ba8acc'
red = '#b84131'
white = '#a1a1a1'
yellow = '#c4a500'

[colors.primary]
background = '#1b1b1b'
foreground = '#f7f7f7'

[colors.selection]
background = '#207483'
text = '#f7f7f7'
