# Colors (Solarized Dark Higher Contrast)

[colors.bright]
black = '#006488'
blue = '#178ec8'
cyan = '#00b39e'
green = '#51ef84'
magenta = '#e24d8e'
red = '#f5163b'
white = '#fcf4dc'
yellow = '#b27e28'

[colors.cursor]
cursor = '#f34b00'
text = '#002831'

[colors.normal]
black = '#002831'
blue = '#2176c7'
cyan = '#259286'
green = '#6cbe6c'
magenta = '#c61c6f'
red = '#d11c24'
white = '#eae3cb'
yellow = '#a57706'

[colors.primary]
background = '#001e27'
foreground = '#9cc2c3'

[colors.selection]
background = '#003748'
text = '#7a8f8e'
