# Colors (SpaceGray)

[colors.bright]
black = '#000000'
blue = '#7d8fa4'
cyan = '#85a7a5'
green = '#87b379'
magenta = '#a47996'
red = '#b04b57'
white = '#ffffff'
yellow = '#e5c179'

[colors.cursor]
cursor = '#b3b8c3'
text = '#1d1f21'

[colors.normal]
black = '#000000'
blue = '#7d8fa4'
cyan = '#85a7a5'
green = '#87b379'
magenta = '#a47996'
red = '#b04b57'
white = '#b3b8c3'
yellow = '#e5c179'

[colors.primary]
background = '#20242d'
foreground = '#b3b8c3'

[colors.selection]
background = '#16181e'
text = '#b3b8c3'
