# Colors (Square)

[colors.bright]
black = '#141414'
blue = '#b6defb'
cyan = '#d7d9fc'
green = '#c3f786'
magenta = '#ad7fa8'
red = '#f99286'
white = '#e2e2e2'
yellow = '#fcfbcc'

[colors.cursor]
cursor = '#fcfbcc'
text = '#000000'

[colors.normal]
black = '#050505'
blue = '#a9cdeb'
cyan = '#c9caec'
green = '#b6377d'
magenta = '#75507b'
red = '#e9897c'
white = '#f2f2f2'
yellow = '#ecebbe'

[colors.primary]
background = '#1a1a1a'
foreground = '#acacab'

[colors.selection]
background = '#4d4d4d'
text = '#ffffff'
