# Colors (tokyonight-storm)

[colors.bright]
black = '#414868'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#c0caf5'
yellow = '#e0af68'

[colors.cursor]
cursor = '#c0caf5'
text = '#1d202f'

[colors.normal]
black = '#1d202f'
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
red = '#f7768e'
white = '#a9b1d6'
yellow = '#e0af68'

[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

[colors.selection]
background = '#364a82'
text = '#c0caf5'
