# Colors (Violet Light)

[colors.bright]
black = '#45484b'
blue = '#2176c7'
cyan = '#259286'
green = '#738a04'
magenta = '#c61c6f'
red = '#bd3613'
white = '#c9c6bd'
yellow = '#a57705'

[colors.cursor]
cursor = '#536870'
text = '#fcf4dc'

[colors.normal]
black = '#56595c'
blue = '#2e8bce'
cyan = '#32a198'
green = '#85981c'
magenta = '#d13a82'
red = '#c94c22'
white = '#d3d0c9'
yellow = '#b4881d'

[colors.primary]
background = '#fcf4dc'
foreground = '#536870'

[colors.selection]
background = '#595ab7'
text = '#fcf4dc'
