[colors]
background = '#1e1e1e'
foreground = '#ffffff'
selection-background = '#ffffff'
selection-foreground = '#5e5c64'
cursor = '#ffffff'
black = '#241f31'
red = '#c01c28'
green = '#2ec27e'
yellow = '#f5c211'
blue = '#1e78e4'
magenta = '#9841bb'
cyan = '#0ab9dc'
white = '#c0bfbc'
light_black = '#5e5c64'
light_red = '#ed333b'
light_green = '#57e389'
light_yellow = '#f8e45c'
light_blue = '#51a1ff'
light_magenta = '#c061cb'
light_cyan = '#4fd2fd'
light_white = '#f6f5f4'
