[colors]
background = '#f0f2f6'
foreground = '#4a4d66'
selection-background = '#bdc2cc'
selection-foreground = '#4a4d66'
cursor = '#fc6008'
black = '#f0f2f6'
red = '#d00c36'
green = '#3e9e28'
yellow = '#dd8c1a'
blue = '#1c64f2'
magenta = '#8636ec'
cyan = '#159096'
white = '#4a4d66'
light_black = '#adb2bc'
light_red = '#d00c36'
light_green = '#3e9e28'
light_yellow = '#dd8c1a'
light_blue = '#1c64f2'
light_magenta = '#8636ec'
light_cyan = '#159096'
light_white = '#4a4d66'
