[colors]
background = '#1a1a1a'
foreground = '#d0d6f0'
selection-background = '#333333'
selection-foreground = '#d0d6f0'
cursor = '#f8b080'
black = '#1a1a1a'
red = '#f08898'
green = '#a4e09c'
yellow = '#f5dea4'
blue = '#84b4f8'
magenta = '#c8a2f4'
cyan = '#90dcd0'
white = '#d0d6f0'
light_black = '#444444'
light_red = '#f08898'
light_green = '#a4e09c'
light_yellow = '#f5dea4'
light_blue = '#84b4f8'
light_magenta = '#c8a2f4'
light_cyan = '#90dcd0'
light_white = '#ffffff'
