[colors]
background = '#feffff'
foreground = '#000000'
selection-background = '#abd8ff'
selection-foreground = '#000000'
cursor = '#98989d'
black = '#1a1a1a'
red = '#cc372e'
green = '#26a439'
yellow = '#cdac08'
blue = '#0869cb'
magenta = '#9647bf'
cyan = '#479ec2'
white = '#98989d'
light_black = '#464646'
light_red = '#ff453a'
light_green = '#32d74b'
light_yellow = '#edbb00'
light_blue = '#0a84ff'
light_magenta = '#bf5af2'
light_cyan = '#3accf7'
light_white = '#ffffff'
