[colors]
background = '#ffffff'
foreground = '#000000'
selection-background = '#b5d5ff'
selection-foreground = '#000000'
cursor = '#000000'
black = '#000000'
red = '#bb0000'
green = '#00bb00'
yellow = '#bbbb00'
blue = '#0000bb'
magenta = '#bb00bb'
cyan = '#00bbbb'
white = '#bbbbbb'
light_black = '#555555'
light_red = '#ff5555'
light_green = '#55ff55'
light_yellow = '#ffff55'
light_blue = '#5555ff'
light_magenta = '#ff55ff'
light_cyan = '#55ffff'
light_white = '#ffffff'
