[colors]
background = '#f2ecbc'
foreground = '#545464'
selection-background = '#545464'
selection-foreground = '#f2ecbc'
cursor = '#43436c'
black = '#1f1f28'
red = '#c84053'
green = '#6f894e'
yellow = '#77713f'
blue = '#4d699b'
magenta = '#b35b79'
cyan = '#597b75'
white = '#545464'
light_black = '#8a8980'
light_red = '#d7474b'
light_green = '#6e915f'
light_yellow = '#836f4a'
light_blue = '#6693bf'
light_magenta = '#624c83'
light_cyan = '#5e857a'
light_white = '#43436c'
