[colors]
background = '#22262d'
foreground = '#c5c9c7'
selection-background = '#43464e'
selection-foreground = '#c5c9c7'
cursor = '#c5c9c7'
black = '#22262d'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#a4a7a4'
light_black = '#5c6066'
light_red = '#e46876'
light_green = '#87a987'
light_yellow = '#e6c384'
light_blue = '#7fb4ca'
light_magenta = '#938aa9'
light_cyan = '#7aa89f'
light_white = '#c5c9c7'
