[colors]
background = '#303030'
foreground = '#afc2c2'
selection-background = '#7dbeff'
selection-foreground = '#000000'
cursor = '#ffffff'
black = '#000000'
red = '#ff3030'
green = '#559a70'
yellow = '#ccac00'
blue = '#0099cc'
magenta = '#cc69c8'
cyan = '#7ac4cc'
white = '#bccccc'
light_black = '#000000'
light_red = '#ff3030'
light_green = '#559a70'
light_yellow = '#ccac00'
light_blue = '#0099cc'
light_magenta = '#cc69c8'
light_cyan = '#7ac4cc'
light_white = '#bccccc'
