[colors]
background = '#fef49c'
foreground = '#000000'
selection-background = '#a4c9cd'
selection-foreground = '#000000'
cursor = '#7f7f7f'
black = '#000000'
red = '#cc0000'
green = '#00a600'
yellow = '#999900'
blue = '#0000b2'
magenta = '#b200b2'
cyan = '#00a6b2'
white = '#cccccc'
light_black = '#666666'
light_red = '#e50000'
light_green = '#00d900'
light_yellow = '#e5e500'
light_blue = '#0000ff'
light_magenta = '#e500e5'
light_cyan = '#00e5e5'
light_white = '#e5e5e5'
