[colors]
background = '#0d0e1c'
foreground = '#ffffff'
selection-background = '#555a66'
selection-foreground = '#ffffff'
cursor = '#ff66ff'
black = '#0d0e1c'
red = '#ff5f59'
green = '#44bc44'
yellow = '#d0bc00'
blue = '#2fafff'
magenta = '#feacd0'
cyan = '#00d3d0'
white = '#a6a6a6'
light_black = '#595959'
light_red = '#ff6b55'
light_green = '#00c06f'
light_yellow = '#fec43f'
light_blue = '#79a8ff'
light_magenta = '#b6a0ff'
light_cyan = '#6ae4b9'
light_white = '#ffffff'
