[colors]
background = '#ffffff'
foreground = '#000000'
selection-background = '#bdbdbd'
selection-foreground = '#000000'
cursor = '#000000'
black = '#000000'
red = '#a60000'
green = '#006800'
yellow = '#6f5500'
blue = '#0031a9'
magenta = '#721045'
cyan = '#005e8b'
white = '#a6a6a6'
light_black = '#595959'
light_red = '#972500'
light_green = '#00663f'
light_yellow = '#884900'
light_blue = '#3548cf'
light_magenta = '#531ab6'
light_cyan = '#005f5f'
light_white = '#595959'
