[colors]
background = '#000000'
foreground = '#ffffff'
selection-background = '#5a5a5a'
selection-foreground = '#ffffff'
cursor = '#ffffff'
black = '#000000'
red = '#ff5f59'
green = '#44bc44'
yellow = '#d0bc00'
blue = '#2fafff'
magenta = '#feacd0'
cyan = '#00d3d0'
white = '#a6a6a6'
light_black = '#595959'
light_red = '#ff7f9f'
light_green = '#00c06f'
light_yellow = '#fec43f'
light_blue = '#79a8ff'
light_magenta = '#b6a0ff'
light_cyan = '#6ae4b9'
light_white = '#ffffff'
