[colors]
background = '#1a1a1a'
foreground = '#c4c5b5'
selection-background = '#343434'
selection-foreground = '#c4c5b5'
cursor = '#f6f7ec'
black = '#1a1a1a'
red = '#f4005f'
green = '#98e024'
yellow = '#fa8419'
blue = '#9d65ff'
magenta = '#f4005f'
cyan = '#58d1eb'
white = '#c4c5b5'
light_black = '#625e4c'
light_red = '#f4005f'
light_green = '#98e024'
light_yellow = '#e0d561'
light_blue = '#9d65ff'
light_magenta = '#f4005f'
light_cyan = '#58d1eb'
light_white = '#f6f6ef'
