[colors]
background = '#241d1a'
foreground = '#c7b8ac'
selection-background = '#c7b8ac'
selection-foreground = '#241d1a'
cursor = '#c7b8ac'
black = '#282a2e'
red = '#9f6434'
green = '#9dac5f'
yellow = '#cca75f'
blue = '#2f7d7c'
magenta = '#b5896e'
cyan = '#52877f'
white = '#c7b8ac'
light_black = '#5d4e47'
light_red = '#9f6434'
light_green = '#9dac5f'
light_yellow = '#cca75f'
light_blue = '#2f7d7c'
light_magenta = '#b5896e'
light_cyan = '#52877f'
light_white = '#c7b8ac'
