[colors]
background = '#21252b'
foreground = '#e6e6e6'
selection-background = '#393e47'
selection-foreground = '#e6e6e6'
cursor = '#e6e6e6'
black = '#1d1f23'
red = '#e27881'
green = '#98c379'
yellow = '#eac786'
blue = '#71b9f4'
magenta = '#c88bda'
cyan = '#62bac6'
white = '#c9ccd3'
light_black = '#4a505a'
light_red = '#e68991'
light_green = '#a8cc8e'
light_yellow = '#edcf97'
light_blue = '#8dc7f6'
light_magenta = '#d3a2e2'
light_cyan = '#78c4ce'
light_white = '#e6e6e6'
