[colors]
background = '#f7f8fa'
foreground = '#2e3440'
selection-background = '#eaebed'
selection-foreground = '#000000'
cursor = '#3879c5'
black = '#2e3440'
red = '#cb4f53'
green = '#48a53d'
yellow = '#ee5e25'
blue = '#3879c5'
magenta = '#9f4aca'
cyan = '#3ea1ad'
white = '#b2b6bd'
light_black = '#646a76'
light_red = '#d16366'
light_green = '#5f9e9d'
light_yellow = '#ba793e'
light_blue = '#1b40a6'
light_magenta = '#9665af'
light_cyan = '#8fbcbb'
light_white = '#eceff4'
