[colors]
background = '#2e3440'
foreground = '#e5e9f0'
selection-background = '#434c5e'
selection-foreground = '#d8dee9'
cursor = '#81a1c1'
black = '#3b4252'
red = '#e06c75'
green = '#9ec183'
yellow = '#ebcb8b'
blue = '#81a1c1'
magenta = '#b988b0'
cyan = '#88c0d0'
white = '#e5e9f0'
light_black = '#596377'
light_red = '#e06c75'
light_green = '#9ec183'
light_yellow = '#ebcb8b'
light_blue = '#81a1c1'
light_magenta = '#b988b0'
light_cyan = '#8fbcbb'
light_white = '#eceff4'
