[colors]
background = '#161616'
foreground = '#f2f4f8'
selection-background = '#393939'
selection-foreground = '#161616'
cursor = '#ffffff'
black = '#161616'
red = '#3ddbd9'
green = '#33b1ff'
yellow = '#ee5396'
blue = '#42be65'
magenta = '#be95ff'
cyan = '#ff7eb6'
white = '#f2f4f8'
light_black = '#585858'
light_red = '#3ddbd9'
light_green = '#33b1ff'
light_yellow = '#ee5396'
light_blue = '#42be65'
light_magenta = '#be95ff'
light_cyan = '#ff7eb6'
light_white = '#f2f4f8'
