[colors]
background = '#161616'
foreground = '#f2f4f8'
selection-background = '#393939'
selection-foreground = '#636262'
cursor = '#ffffff'
black = '#161616'
red = '#00dfdb'
green = '#00b4ff'
yellow = '#ff4297'
blue = '#00c15a'
magenta = '#c693ff'
cyan = '#ff74b8'
white = '#f2f4f8'
light_black = '#585858'
light_red = '#00dfdb'
light_green = '#00b4ff'
light_yellow = '#ff4297'
light_blue = '#00c15a'
light_magenta = '#c693ff'
light_cyan = '#ff74b8'
light_white = '#f2f4f8'
