[colors]
background = '#252b37'
foreground = '#a6accd'
selection-background = '#a6accd'
selection-foreground = '#ffffff'
cursor = '#ffffff'
black = '#252b37'
red = '#d0679d'
green = '#5de4c7'
yellow = '#fffac2'
blue = '#89ddff'
magenta = '#f087bd'
cyan = '#89ddff'
white = '#ffffff'
light_black = '#a6accd'
light_red = '#d0679d'
light_green = '#5de4c7'
light_yellow = '#fffac2'
light_blue = '#add7ff'
light_magenta = '#f087bd'
light_cyan = '#add7ff'
light_white = '#ffffff'
