[colors]
background = '#fefeff'
foreground = '#969cbd'
selection-background = '#969cbd'
selection-foreground = '#3b3e48'
cursor = '#969cbd'
black = '#fefeff'
red = '#ff2090'
green = '#01dab2'
yellow = '#e5ba4e'
blue = '#8abacd'
magenta = '#eb8394'
cyan = '#8abacd'
white = '#000000'
light_black = '#969cbd'
light_red = '#ff2090'
light_green = '#01dab2'
light_yellow = '#e5ba4e'
light_blue = '#0ebfff'
light_magenta = '#eb8394'
light_cyan = '#0ebfff'
light_white = '#000000'
