[colors]
background = '#181818'
foreground = '#b9b9b9'
selection-background = '#3b3b3b'
selection-foreground = '#646464'
cursor = '#777777'
black = '#252525'
red = '#ed4a46'
green = '#70b433'
yellow = '#dbb32d'
blue = '#368aeb'
magenta = '#eb6eb7'
cyan = '#3fc5b7'
white = '#b9b9b9'
light_black = '#777777'
light_red = '#ff5e56'
light_green = '#83c746'
light_yellow = '#efc541'
light_blue = '#4f9cfe'
light_magenta = '#ff81ca'
light_cyan = '#56d8c9'
light_white = '#dedede'
