[colors]
background = '#0f0f1a'
foreground = '#ededfe'
selection-background = '#202036'
selection-foreground = '#ededff'
cursor = '#ededfe'
black = '#0a0a13'
red = '#ff0063'
green = '#00f992'
yellow = '#ffe900'
blue = '#00a4ff'
magenta = '#ff57fd'
cyan = '#00ffed'
white = '#ededff'
light_black = '#3e3e4b'
light_red = '#ff948b'
light_green = '#00fcb9'
light_yellow = '#ffff68'
light_blue = '#3ea0ff'
light_magenta = '#ff93ff'
light_cyan = '#38ffff'
light_white = '#f8f8ff'
