[colors]
background = '#f8f8ff'
foreground = '#1d1d26'
selection-background = '#ff3399'
selection-foreground = '#ffffff'
cursor = '#cbcbf0'
black = '#1d1d26'
red = '#ff3399'
green = '#00d364'
yellow = '#ffcc66'
blue = '#00cbff'
magenta = '#cc66ff'
cyan = '#00ceca'
white = '#cbcbf0'
light_black = '#636667'
light_red = '#ff2f92'
light_green = '#00d364'
light_yellow = '#ffd479'
light_blue = '#00cbff'
light_magenta = '#d783ff'
light_cyan = '#00d5d4'
light_white = '#d5d6f3'
