[colors]
background = '#1a1b26'
foreground = '#c0caf5'
selection-background = '#33467c'
selection-foreground = '#c0caf5'
cursor = '#c0caf5'
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'
light_black = '#414868'
light_red = '#f7768e'
light_green = '#9ece6a'
light_yellow = '#e0af68'
light_blue = '#7aa2f7'
light_magenta = '#bb9af7'
light_cyan = '#7dcfff'
light_white = '#c0caf5'
