[colors]
background = '#272c30'
foreground = '#cfb9a8'
selection-background = '#cfb9a8'
selection-foreground = '#272c30'
cursor = '#cfb9a8'
black = '#282d31'
red = '#934e46'
green = '#637268'
yellow = '#c79e84'
blue = '#515e67'
magenta = '#715f5e'
cyan = '#5c6f7d'
white = '#cfb9a8'
light_black = '#4e575e'
light_red = '#934e46'
light_green = '#637270'
light_yellow = '#c79e84'
light_blue = '#515e67'
light_magenta = '#715f5e'
light_cyan = '#5c6f7d'
light_white = '#ddcec2'
