[colors]
background = '#312e39'
foreground = '#c0a79a'
selection-background = '#c0a79a'
selection-foreground = '#312e39'
cursor = '#c0a79a'
black = '#33303b'
red = '#87404f'
green = '#74934e'
yellow = '#ae835a'
blue = '#615772'
magenta = '#854b64'
cyan = '#625464'
white = '#c0a79a'
light_black = '#5c5865'
light_red = '#87404f'
light_green = '#74934e'
light_yellow = '#ae835a'
light_blue = '#615772'
light_magenta = '#854b64'
light_cyan = '#625464'
light_white = '#c0a79a'
