[colors]
background = '#fcf4dc'
foreground = '#536870'
selection-background = '#595ab7'
selection-foreground = '#fcf4dc'
cursor = '#536870'
black = '#56595c'
red = '#c94c22'
green = '#85981c'
yellow = '#b4881d'
blue = '#2e8bce'
magenta = '#d13a82'
cyan = '#32a198'
white = '#d3d0c9'
light_black = '#45484b'
light_red = '#bd3613'
light_green = '#738a04'
light_yellow = '#a57705'
light_blue = '#2176c7'
light_magenta = '#c61c6f'
light_cyan = '#259286'
light_white = '#c9c6bd'
