# Apple System Colors Light
[colors]
foreground = "#000000"
background = "#feffff"
cursor_bg = "#98989d"
cursor_border = "#98989d"
cursor_fg = "#ffffff"
selection_bg = "#abd8ff"
selection_fg = "#000000"

ansi = ["#1a1a1a","#cc372e","#26a439","#cdac08","#0869cb","#9647bf","#479ec2","#98989d"]
brights = ["#464646","#ff453a","#32d74b","#e5bc00","#0a84ff","#bf5af2","#69c9f2","#ffffff"]
