# Batman
[colors]
foreground = "#6f6f6f"
background = "#1b1d1e"
cursor_bg = "#fcef0c"
cursor_border = "#fcef0c"
cursor_fg = "#000000"
selection_bg = "#4d504c"
selection_fg = "#f0e04a"

ansi = ["#1b1d1e","#e6dc44","#c8be46","#f4fd22","#737174","#747271","#62605f","#c6c5bf"]
brights = ["#505354","#fff78e","#fff27d","#feed6c","#919495","#9a9a9d","#a3a3a6","#dadbd6"]
