# branch
[colors]
foreground = "#cfc1a9"
background = "#32221a"
cursor_bg = "#cfc1a9"
cursor_border = "#cfc1a9"
cursor_fg = "#32221a"
selection_bg = "#cfc1a9"
selection_fg = "#32221a"

ansi = ["#35241c","#c2562d","#96a65e","#d29b5a","#3b8e8c","#c47e5b","#639a90","#cfc1a9"]
brights = ["#564a45","#c2562d","#96a65e","#d29b5a","#3b8e8c","#c47e5b","#639a90","#cfc1a9"]
