# Builtin Light
[colors]
foreground = "#000000"
background = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#ffffff"
selection_bg = "#b5d5ff"
selection_fg = "#000000"

ansi = ["#000000","#bb0000","#00bb00","#bbbb00","#0000bb","#bb00bb","#00bbbb","#bbbbbb"]
brights = ["#555555","#ff5555","#55ff55","#ffff55","#5555ff","#ff55ff","#55ffff","#ffffff"]
