# Calamity
[colors]
foreground = "#d5ced9"
background = "#2f2833"
cursor_bg = "#d5ced9"
cursor_border = "#d5ced9"
cursor_fg = "#2f2833"
selection_bg = "#7e6c88"
selection_fg = "#d5ced9"

ansi = ["#2f2833","#fc644d","#a5f69c","#e9d7a5","#3b79c7","#f92672","#74d3de","#d5ced9"]
brights = ["#7e6c88","#fc644d","#a5f69c","#e9d7a5","#3b79c7","#f92672","#74d3de","#ffffff"]
