# catppuccin-mocha
[colors]
foreground = "#cdd6f4"
background = "#1e1e2e"
cursor_bg = "#f5e0dc"
cursor_border = "#f5e0dc"
cursor_fg = "#1e1e2e"
selection_bg = "#585b70"
selection_fg = "#cdd6f4"

ansi = ["#45475a","#f38ba8","#a6e3a1","#f9e2af","#89b4fa","#f5c2e7","#94e2d5","#a6adc8"]
brights = ["#585b70","#f37799","#89d88b","#ebd391","#74a8fc","#f2aede","#6bd7ca","#bac2de"]
