# Cobalt Next Dark
[colors]
foreground = "#d7deea"
background = "#0b1c24"
cursor_bg = "#ffc64c"
cursor_border = "#ffc64c"
cursor_fg = "#999999"
selection_bg = "#37b5b4"
selection_fg = "#ffffff"

ansi = ["#262f37","#f94967","#8cc98f","#ffc64c","#409dd4","#cba3c7","#37b5b4","#d7deea"]
brights = ["#62747f","#e47e8b","#baddbb","#ffdc91","#7ac0eb","#f3ccef","#84e4e3","#ffffff"]
