# Dark+
[colors]
foreground = "#cccccc"
background = "#1e1e1e"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#3a3d41"
selection_fg = "#e0e0e0"

ansi = ["#000000","#cd3131","#0dbc79","#e5e510","#2472c8","#bc3fbc","#11a8cd","#e5e5e5"]
brights = ["#666666","#f14c4c","#23d18b","#f5f543","#3b8eea","#d670d6","#29b8db","#e5e5e5"]
