# Dawnfox
[colors]
foreground = "#575279"
background = "#faf4ed"
cursor_bg = "#575279"
cursor_border = "#575279"
cursor_fg = "#faf4ed"
selection_bg = "#d0d8d8"
selection_fg = "#575279"

ansi = ["#575279","#b4637a","#618774","#ea9d34","#286983","#907aa9","#56949f","#b2b6bd"]
brights = ["#5f5695","#c26d85","#629f81","#eea846","#2d81a3","#9a80b9","#5ca7b4","#e6ebf3"]
