# DjangoRebornAgain
[colors]
foreground = "#dadedc"
background = "#051f14"
cursor_bg = "#ffcc00"
cursor_border = "#ffcc00"
cursor_fg = "#dadedc"
selection_bg = "#203727"
selection_fg = "#dadedc"

ansi = ["#000000","#fd6209","#41a83e","#ffe862","#245032","#f8f8f8","#9df39f","#ffffff"]
brights = ["#323232","#ff943b","#73da70","#ffff94","#568264","#ffffff","#cfffd1","#ffffff"]
