# Duskfox
[colors]
foreground = "#e0def4"
background = "#232136"
cursor_bg = "#e0def4"
cursor_border = "#e0def4"
cursor_fg = "#232136"
selection_bg = "#433c59"
selection_fg = "#e0def4"

ansi = ["#393552","#eb6f92","#a3be8c","#f6c177","#569fba","#c4a7e7","#9ccfd8","#e0def4"]
brights = ["#47407d","#f083a2","#b1d196","#f9cb8c","#65b1cd","#ccb1ed","#a6dae3","#e2e0f7"]
