# Elemental
[colors]
foreground = "#807a74"
background = "#22211d"
cursor_bg = "#facb80"
cursor_border = "#facb80"
cursor_fg = "#161611"
selection_bg = "#413829"
selection_fg = "#facd77"

ansi = ["#3c3c30","#98290f","#479a43","#7f7111","#497f7d","#7f4e2f","#387f58","#807974"]
brights = ["#555445","#e0502a","#61e070","#d69927","#79d9d9","#cd7c54","#59d599","#fff1e9"]
