# Everforest Dark - Hard
[colors]
foreground = "#d3c6aa"
background = "#1e2326"
cursor_bg = "#e69875"
cursor_border = "#e69875"
cursor_fg = "#4c3743"
selection_bg = "#4c3743"
selection_fg = "#d3c6aa"

ansi = ["#7a8478","#e67e80","#a7c080","#dbbc7f","#7fbbb3","#d699b6","#83c092","#f2efdf"]
brights = ["#a6b0a0","#f85552","#8da101","#dfa000","#3a94c5","#df69ba","#35a77c","#fffbef"]
