# Fideloper
[colors]
foreground = "#dbdae0"
background = "#292f33"
cursor_bg = "#d4605a"
cursor_border = "#d4605a"
cursor_fg = "#fefff2"
selection_bg = "#efb8ac"
selection_fg = "#ffffff"

ansi = ["#292f33","#cb1e2d","#edb8ac","#b7ab9b","#2e78c2","#c0236f","#309186","#eae3ce"]
brights = ["#092028","#d4605a","#d4605a","#a86671","#7c85c4","#5c5db2","#819090","#fcf4df"]
