# Floraverse
[colors]
foreground = "#dbd1b9"
background = "#0e0d15"
cursor_bg = "#bbbbbb"
cursor_border = "#bbbbbb"
cursor_fg = "#ffffff"
selection_bg = "#f3e0b8"
selection_fg = "#08002e"

ansi = ["#08002e","#64002c","#5d731a","#cd751c","#1d6da1","#b7077e","#42a38c","#f3e0b8"]
brights = ["#331e4d","#d02063","#b4ce59","#fac357","#40a4cf","#f12aae","#62caa8","#fff5db"]
