# Ghostty Default Style Dark
[colors]
foreground = "#ffffff"
background = "#282c34"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#353a44"
selection_bg = "#ffffff"
selection_fg = "#282c34"

ansi = ["#1d1f21","#cc6566","#b6bd68","#f0c674","#82a2be","#b294bb","#8abeb7","#c4c8c6"]
brights = ["#666666","#d54e53","#b9ca4b","#e7c547","#7aa6da","#c397d8","#70c0b1","#eaeaea"]
