# Github
[colors]
foreground = "#3e3e3e"
background = "#f4f4f4"
cursor_bg = "#3f3f3f"
cursor_border = "#3f3f3f"
cursor_fg = "#f4f4f4"
selection_bg = "#a9c1e2"
selection_fg = "#535353"

ansi = ["#3e3e3e","#970b16","#07962a","#f8eec7","#003e8a","#e94691","#89d1ec","#ffffff"]
brights = ["#666666","#de0000","#87d5a2","#f1d007","#2e6cba","#ffa29f","#1cfafe","#ffffff"]
