# Gruvbox Material Dark
[colors]
foreground = "#d4be98"
background = "#282828"
cursor_bg = "#d4be98"
cursor_border = "#d4be98"
cursor_fg = "#282828"
selection_bg = "#d4be98"
selection_fg = "#282828"

ansi = ["#282828","#ea6962","#a9b665","#d8a657","#7daea3","#d3869b","#89b482","#d4be98"]
brights = ["#7c6f64","#ea6962","#a9b665","#d8a657","#7daea3","#d3869b","#89b482","#ddc7a1"]
