# Havn Skumring
[colors]
foreground = "#d6dbeb"
background = "#111522"
cursor_bg = "#277a6f"
cursor_border = "#277a6f"
cursor_fg = "#e0e4f3"
selection_bg = "#2b514b"
selection_fg = "#dce0ef"

ansi = ["#252c47","#ea563e","#6ead7b","#f8b330","#596cf7","#7c719e","#d588c1","#dce0ee"]
brights = ["#38425c","#d17264","#8c9e8f","#eac58c","#5186cb","#9b7cee","#d17ab6","#fff6e1"]
