# Heeler
[colors]
foreground = "#fdfdfd"
background = "#211f46"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#2b2c41"
selection_fg = "#2eff58"

ansi = ["#000000","#e44c2e","#bdd100","#f4ce65","#5ba5f2","#ff95c2","#ff9763","#ffffff"]
brights = ["#000000","#e44c2e","#bdd100","#f4ce65","#0088ff","#ff95c2","#8da6e4","#ffffff"]
