# Homebrew
[colors]
foreground = "#00ff00"
background = "#000000"
cursor_bg = "#23ff18"
cursor_border = "#23ff18"
cursor_fg = "#ff0018"
selection_bg = "#083905"
selection_fg = "#ffffff"

ansi = ["#000000","#990000","#00a600","#999900","#0000b2","#b200b2","#00a6b2","#bfbfbf"]
brights = ["#666666","#e50000","#00d900","#e5e500","#0000ff","#e500e5","#00e5e5","#e5e5e5"]
