# Horizon Bright
[colors]
foreground = "#16161d"
background = "#fdf0ed"
cursor_bg = "#f9cec3"
cursor_border = "#f9cec3"
cursor_fg = "#f9cec3"
selection_bg = "#f9cec3"
selection_fg = "#16161d"

ansi = ["#16161d","#fc4777","#00d793","#ffb38f","#00bedd","#ff58b1","#00e7e5","#ffefec"]
brights = ["#1a1c24","#fe5f87","#00dea0","#ffc0a2","#00c9e2","#ff6cba","#07e9e8","#fff2ef"]
