# Hurtado
[colors]
foreground = "#dbdbdb"
background = "#000000"
cursor_bg = "#bbbbbb"
cursor_border = "#bbbbbb"
cursor_fg = "#ffffff"
selection_bg = "#b5d5ff"
selection_fg = "#000000"

ansi = ["#575757","#ff1b00","#a5e055","#fbe74a","#496487","#fd5ff1","#86e9fe","#cbcccb"]
brights = ["#262626","#d51d00","#a5df55","#fbe84a","#89beff","#c001c1","#86eafe","#dbdbdb"]
