# iTerm2 Solarized Dark
[colors]
foreground = "#839496"
background = "#002b36"
cursor_bg = "#839496"
cursor_border = "#839496"
cursor_fg = "#073642"
selection_bg = "#073642"
selection_fg = "#93a1a1"

ansi = ["#073642","#dc322f","#859900","#b58900","#268bd2","#d33682","#2aa198","#eee8d5"]
brights = ["#002b36","#cb4b16","#586e75","#657b83","#839496","#6c71c4","#93a1a1","#fdf6e3"]
