# Japanesque
[colors]
foreground = "#f7f6ec"
background = "#1e1e1e"
cursor_bg = "#edcf4f"
cursor_border = "#edcf4f"
cursor_fg = "#343935"
selection_bg = "#175877"
selection_fg = "#f7f6ec"

ansi = ["#343935","#cf3f61","#7bb75b","#e9b32a","#4c9ad4","#a57fc4","#389aad","#fafaf6"]
brights = ["#595b59","#d18fa6","#767f2c","#78592f","#135979","#604291","#76bbca","#b2b5ae"]
