# Kanagawa Lotus
[colors]
foreground = "#545464"
background = "#f2ecbc"
cursor_bg = "#43436c"
cursor_border = "#43436c"
cursor_fg = "#f2ecbc"
selection_bg = "#545464"
selection_fg = "#f2ecbc"

ansi = ["#1f1f28","#c84053","#6f894e","#77713f","#4d699b","#b35b79","#597b75","#545464"]
brights = ["#8a8980","#d7474b","#6e915f","#836f4a","#6693bf","#624c83","#5e857a","#43436c"]
