# Kanagawa Wave
[colors]
foreground = "#dcd7ba"
background = "#1f1f28"
cursor_bg = "#dcd7ba"
cursor_border = "#dcd7ba"
cursor_fg = "#1f1f28"
selection_bg = "#dcd7ba"
selection_fg = "#1f1f28"

ansi = ["#090618","#c34043","#76946a","#c0a36e","#7e9cd8","#957fb8","#6a9589","#c8c093"]
brights = ["#727169","#e82424","#98bb6c","#e6c384","#7fb4ca","#938aa9","#7aa89f","#dcd7ba"]
