# Kanso Ink
[colors]
foreground = "#c5c9c7"
background = "#14171d"
cursor_bg = "#c5c9c7"
cursor_border = "#c5c9c7"
cursor_fg = "#14171d"
selection_bg = "#22262d"
selection_fg = "#c5c9c7"

ansi = ["#14171d","#c4746e","#8a9a7b","#c4b28a","#8ba4b0","#a292a3","#8ea4a2","#c8c093"]
brights = ["#a4a7a4","#e46876","#87a987","#e6c384","#7fb4ca","#938aa9","#7aa89f","#c5c9c7"]
