# Lab Fox
[colors]
foreground = "#ffffff"
background = "#2e2e2e"
cursor_bg = "#7f7f7f"
cursor_border = "#7f7f7f"
cursor_fg = "#7f7f7f"
selection_bg = "#cb392e"
selection_fg = "#ffffff"

ansi = ["#2e2e2e","#fc6d26","#3eb383","#fca121","#db3b21","#380d75","#6e49cb","#ffffff"]
brights = ["#464646","#ff6517","#53eaa8","#fca013","#db501f","#441090","#7d53e7","#ffffff"]
