# Later This Evening
[colors]
foreground = "#959595"
background = "#222222"
cursor_bg = "#424242"
cursor_border = "#424242"
cursor_fg = "#959595"
selection_bg = "#424242"
selection_fg = "#959595"

ansi = ["#2b2b2b","#d45a60","#afba67","#e5d289","#a0bad6","#c092d6","#91bfb7","#3c3d3d"]
brights = ["#454747","#d3232f","#aabb39","#e5be39","#6699d6","#ab53d6","#5fc0ae","#c1c2c2"]
