# MaterialDesignColors
[colors]
foreground = "#e7ebed"
background = "#1d262a"
cursor_bg = "#eaeaea"
cursor_border = "#eaeaea"
cursor_fg = "#000000"
selection_bg = "#4e6a78"
selection_fg = "#e7ebed"

ansi = ["#435b67","#fc3841","#5cf19e","#fed032","#37b6ff","#fc226e","#59ffd1","#ffffff"]
brights = ["#a1b0b8","#fc746d","#adf7be","#fee16c","#70cfff","#fc669b","#9affe6","#ffffff"]
