# Melange_dark
[colors]
foreground = "#ece1d7"
background = "#292522"
cursor_bg = "#ece1d7"
cursor_border = "#ece1d7"
cursor_fg = "#292522"
selection_bg = "#ece1d7"
selection_fg = "#403a36"

ansi = ["#34302c","#bd8183","#78997a","#e49b5d","#7f91b2","#b380b0","#7b9695","#c1a78e"]
brights = ["#867462","#d47766","#85b695","#ebc06d","#a3a9ce","#cf9bc2","#89b3b6","#ece1d7"]
