# mellow
[colors]
foreground = "#c9c7cd"
background = "#161617"
cursor_bg = "#cac9dd"
cursor_border = "#cac9dd"
cursor_fg = "#161617"
selection_bg = "#2a2a2d"
selection_fg = "#c1c0d4"

ansi = ["#27272a","#f5a191","#90b99f","#e6b99d","#aca1cf","#e29eca","#ea83a5","#c1c0d4"]
brights = ["#353539","#ffae9f","#9dc6ac","#f0c5a9","#b9aeda","#ecaad6","#f591b2","#cac9dd"]
