# Modus Vivendi
[colors]
foreground = "#ffffff"
background = "#000000"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#5a5a5a"
selection_fg = "#ffffff"

ansi = ["#000000","#ff5f59","#44bc44","#d0bc00","#2fafff","#feacd0","#00d3d0","#a6a6a6"]
brights = ["#595959","#ff7f9f","#00c06f","#fec43f","#79a8ff","#b6a0ff","#6ae4b9","#ffffff"]
