# Night Owlish Light
[colors]
foreground = "#403f53"
background = "#ffffff"
cursor_bg = "#403f53"
cursor_border = "#403f53"
cursor_fg = "#fbfbfb"
selection_bg = "#f2f2f2"
selection_fg = "#403f53"

ansi = ["#011627","#d3423e","#2aa298","#daaa01","#4876d6","#403f53","#08916a","#7a8181"]
brights = ["#7a8181","#f76e6e","#49d0c5","#dac26b","#5ca7e4","#697098","#00c990","#989fb1"]
