# Nocturnal Winter
[colors]
foreground = "#e6e5e5"
background = "#0d0d17"
cursor_bg = "#e6e5e5"
cursor_border = "#e6e5e5"
cursor_fg = "#ffffff"
selection_bg = "#adbdd0"
selection_fg = "#000000"

ansi = ["#4d4d4d","#f12d52","#09cd7e","#f5f17a","#3182e0","#ff2b6d","#09c87a","#fcfcfc"]
brights = ["#808080","#f16d86","#0ae78d","#fffc67","#6096ff","#ff78a2","#0ae78d","#ffffff"]
