# Nordfox
[colors]
foreground = "#cdcecf"
background = "#2e3440"
cursor_bg = "#cdcecf"
cursor_border = "#cdcecf"
cursor_fg = "#2e3440"
selection_bg = "#3e4a5b"
selection_fg = "#cdcecf"

ansi = ["#3b4252","#bf616a","#a3be8c","#ebcb8b","#81a1c1","#b48ead","#88c0d0","#e5e9f0"]
brights = ["#465780","#d06f79","#b1d196","#f0d399","#8cafd2","#c895bf","#93ccdc","#e7ecf4"]
