# Oceanic Next
[colors]
foreground = "#c0c5ce"
background = "#162c35"
cursor_bg = "#c0c5ce"
cursor_border = "#c0c5ce"
cursor_fg = "#1b2b34"
selection_bg = "#4f5b66"
selection_fg = "#c0c5ce"

ansi = ["#162c35","#ec5f67","#99c794","#fac863","#6699cc","#c594c5","#5fb3b3","#ffffff"]
brights = ["#65737e","#ec5f67","#99c794","#fac863","#6699cc","#c594c5","#5fb3b3","#ffffff"]
