# One Dark Two
[colors]
foreground = "#e6e6e6"
background = "#21252b"
cursor_bg = "#e6e6e6"
cursor_border = "#e6e6e6"
cursor_fg = "#1d1f23"
selection_bg = "#393e47"
selection_fg = "#e6e6e6"

ansi = ["#1d1f23","#e27881","#98c379","#eac786","#71b9f4","#c88bda","#62bac6","#c9ccd3"]
brights = ["#4a505a","#e68991","#a8cc8e","#edcf97","#8dc7f6","#d3a2e2","#78c4ce","#e6e6e6"]
