# One Double Dark
[colors]
foreground = "#dbdfe5"
background = "#282c34"
cursor_bg = "#f5e0dc"
cursor_border = "#f5e0dc"
cursor_fg = "#9aa3c1"
selection_bg = "#585b70"
selection_fg = "#cdd6f4"

ansi = ["#3d4452","#f16372","#8cc570","#ecbe70","#3fb1f5","#d373e3","#17b9c4","#dbdfe5"]
brights = ["#525d6f","#ff777b","#82d882","#f5c065","#6dcaff","#ff7bf4","#00e5fb","#f7f9fc"]
