# One Half Dark
[colors]
foreground = "#dcdfe4"
background = "#282c34"
cursor_bg = "#a3b3cc"
cursor_border = "#a3b3cc"
cursor_fg = "#e9ecf1"
selection_bg = "#474e5d"
selection_fg = "#dcdfe4"

ansi = ["#282c34","#e06c75","#98c379","#e5c07b","#61afef","#c678dd","#56b6c2","#dcdfe4"]
brights = ["#5d677a","#e06c75","#98c379","#e5c07b","#61afef","#c678dd","#56b6c2","#dcdfe4"]
