# Oxocarbon
[colors]
foreground = "#f2f4f8"
background = "#161616"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#393939"
selection_fg = "#636262"

ansi = ["#161616","#00dfdb","#00b4ff","#ff4297","#00c15a","#c693ff","#ff74b8","#f2f4f8"]
brights = ["#585858","#00dfdb","#00b4ff","#ff4297","#00c15a","#c693ff","#ff74b8","#f2f4f8"]
