# Pandora
[colors]
foreground = "#e1e1e1"
background = "#141e43"
cursor_bg = "#43d58e"
cursor_border = "#43d58e"
cursor_fg = "#ffffff"
selection_bg = "#2d37ff"
selection_fg = "#82e0ff"

ansi = ["#000000","#ff4242","#74af68","#ffad29","#338f86","#9414e6","#23d7d7","#e2e2e2"]
brights = ["#3f5648","#ff3242","#74cd68","#ffb929","#23d7d7","#ff37ff","#00ede1","#ffffff"]
