# PaulMillr
[colors]
foreground = "#f2f2f2"
background = "#000000"
cursor_bg = "#4d4d4d"
cursor_border = "#4d4d4d"
cursor_fg = "#ffffff"
selection_bg = "#414141"
selection_fg = "#ffffff"

ansi = ["#2a2a2a","#ff0000","#79ff0f","#e7bf00","#396bd7","#b449be","#66ccff","#bbbbbb"]
brights = ["#666666","#ff0080","#66ff66","#f3d64e","#709aed","#db67e6","#7adff2","#ffffff"]
