# Pro Light
[colors]
foreground = "#191919"
background = "#ffffff"
cursor_bg = "#4d4d4d"
cursor_border = "#4d4d4d"
cursor_fg = "#f2f2f2"
selection_bg = "#c1ddff"
selection_fg = "#191919"

ansi = ["#000000","#e5492b","#50d148","#c6c440","#3b75ff","#ed66e8","#4ed2de","#dcdcdc"]
brights = ["#9f9f9f","#ff6640","#61ef57","#f2f156","#0082ff","#ff7eff","#61f7f8","#f2f2f2"]
