# Rippedcasts
[colors]
foreground = "#ffffff"
background = "#2b2b2b"
cursor_bg = "#7f7f7f"
cursor_border = "#7f7f7f"
cursor_fg = "#ffffff"
selection_bg = "#5a647e"
selection_fg = "#f2f2f2"

ansi = ["#000000","#cdaf95","#a8ff60","#bfbb1f","#75a5b0","#ff73fd","#5a647e","#bfbfbf"]
brights = ["#666666","#eecbad","#bcee68","#e5e500","#86bdc9","#e500e5","#8c9bc4","#e5e5e5"]
