# shades-of-purple
[colors]
foreground = "#ffffff"
background = "#1e1d40"
cursor_bg = "#fad000"
cursor_border = "#fad000"
cursor_fg = "#fefff4"
selection_bg = "#b362ff"
selection_fg = "#c2c2c2"

ansi = ["#000000","#d90429","#3ad900","#ffe700","#6943ff","#ff2c70","#00c5c7","#c7c7c7"]
brights = ["#686868","#f92a1c","#43d426","#f1d000","#6871ff","#ff77ff","#79e8fb","#ffffff"]
