# Snazzy
[colors]
foreground = "#ebece6"
background = "#1e1f29"
cursor_bg = "#e4e4e4"
cursor_border = "#e4e4e4"
cursor_fg = "#f6f6f6"
selection_bg = "#81aec6"
selection_fg = "#000000"

ansi = ["#000000","#fc4346","#50fb7c","#f0fb8c","#49baff","#fc4cb4","#8be9fe","#ededec"]
brights = ["#555555","#fc4346","#50fb7c","#f0fb8c","#49baff","#fc4cb4","#8be9fe","#ededec"]
