
# Solarized Light
[colors]
foreground = "#536870"
background = "#fcf4dc"
cursor_bg = "#536870"
ansi = ["#002831","#d11c24","#738a05","#a57706","#2176c7","#c61c6f","#259286","#eae3cb"]
brights = ["#001e27","#bd3613","#475b62","#536870","#708284","#5956ba","#819090","#fcf4dc"]
