# Spiderman
[colors]
foreground = "#e3e3e3"
background = "#1b1d1e"
cursor_bg = "#2c3fff"
cursor_border = "#2c3fff"
cursor_fg = "#000000"
selection_bg = "#070e50"
selection_fg = "#f0272d"

ansi = ["#1b1d1e","#e60813","#e22928","#e24756","#2c3fff","#2435db","#3256ff","#fffef6"]
brights = ["#505354","#ff0325","#ff3338","#fe3a35","#1d50ff","#747cff","#6184ff","#fffff9"]
