# Sunset Drive
[colors]
foreground = "#ededfe"
background = "#0f0f1a"
cursor_bg = "#ededfe"
cursor_border = "#ededfe"
cursor_fg = "#0f0f1a"
selection_bg = "#202036"
selection_fg = "#ededff"

ansi = ["#0a0a13","#ff0063","#00f992","#ffe900","#00a4ff","#ff57fd","#00ffed","#ededff"]
brights = ["#3e3e4b","#ff948b","#00fcb9","#ffff68","#3ea0ff","#ff93ff","#38ffff","#f8f8ff"]
