# The Hulk
[colors]
foreground = "#b5b5b5"
background = "#1b1d1e"
cursor_bg = "#16b61b"
cursor_border = "#16b61b"
cursor_fg = "#000000"
selection_bg = "#4d504c"
selection_fg = "#0b6309"

ansi = ["#1b1d1e","#269d1b","#13ce30","#63e457","#2525f5","#641f74","#378ca9","#d9d8d1"]
brights = ["#505354","#8dff2a","#48ff77","#3afe16","#506b95","#72589d","#4085a6","#e5e6e1"]
