# VibrantInk
[colors]
foreground = "#ffffff"
background = "#000000"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#000000"
selection_bg = "#b5d5ff"
selection_fg = "#000000"

ansi = ["#878787","#ff6600","#ccff04","#ffcc00","#44b4cc","#9933cc","#44b4cc","#f5f5f5"]
brights = ["#555555","#ff0000","#00ff00","#ffff00","#0000ff","#ff00ff","#00ffff","#e5e5e5"]
