# Wryan
[colors]
foreground = "#999993"
background = "#101010"
cursor_bg = "#9e9ecb"
cursor_border = "#9e9ecb"
cursor_fg = "#000000"
selection_bg = "#4d4d4d"
selection_fg = "#ffffff"

ansi = ["#333333","#8c4665","#287373","#7c7c99","#395573","#5e468c","#31658c","#899ca1"]
brights = ["#3d3d3d","#bf4d80","#53a6a6","#9e9ecb","#477ab3","#7e62b3","#6096bf","#c0c0c0"]
