# zenbones_light
[colors]
foreground = "#2c363c"
background = "#f0edec"
cursor_bg = "#2c363c"
cursor_border = "#2c363c"
cursor_fg = "#f0edec"
selection_bg = "#cbd9e3"
selection_fg = "#2c363c"

ansi = ["#f0edec","#a8334c","#4f6c31","#944927","#286486","#88507d","#3b8992","#2c363c"]
brights = ["#cfc1ba","#94253e","#3f5a22","#803d1c","#1d5573","#7b3b70","#2b747c","#4f5e68"]
