tags = ["dark"]

[theme.colors]
background = "#1a1a1a"
foreground = "#d0d6f0"
bright-foreground = "#d0d6f0"

[theme.colors.palette]
0 = "#1a1a1a"
1 = "#f08898"
2 = "#a4e09c"
3 = "#f5dea4"
4 = "#84b4f8"
5 = "#c8a2f4"
6 = "#90dcd0"
7 = "#d0d6f0"
8 = "#444444"
9 = "#f08898"
10 = "#a4e09c"
11 = "#f5dea4"
12 = "#84b4f8"
13 = "#c8a2f4"
14 = "#90dcd0"
15 = "#ffffff"
