tags = ["light"]

[theme.colors]
background = "#feffff"
foreground = "#000000"
bright-foreground = "#000000"

[theme.colors.palette]
0 = "#1a1a1a"
1 = "#bc4437"
2 = "#51a148"
3 = "#c7ad3a"
4 = "#2e68c5"
5 = "#8c4bb8"
6 = "#5e9cbe"
7 = "#98989d"
8 = "#464646"
9 = "#eb5545"
10 = "#6bd45f"
11 = "#f8d84a"
12 = "#3b82f7"
13 = "#b260ea"
14 = "#8dd3fb"
15 = "#ffffff"
