tags = ["dark"]

[theme.colors]
background = "#40318d"
foreground = "#7869c4"
bright-foreground = "#a5a2a2"

[theme.colors.palette]
0 = "#090300"
1 = "#a2534c"
2 = "#55a049"
3 = "#bfce72"
4 = "#6657b3"
5 = "#984ca3"
6 = "#67b6bd"
7 = "#ffffff"
8 = "#000000"
9 = "#a2534c"
10 = "#55a049"
11 = "#bfce72"
12 = "#6657b3"
13 = "#984ca3"
14 = "#67b6bd"
15 = "#f7f7f7"
