tags = ["dark"]

[theme.colors]
background = "#070c0e"
foreground = "#35451a"
bright-foreground = "#00cd6d"

[theme.colors.palette]
0 = "#091013"
1 = "#1a4832"
2 = "#6fa64c"
3 = "#595900"
4 = "#00cb6b"
5 = "#4e375a"
6 = "#125459"
7 = "#1a4833"
8 = "#404040"
9 = "#0d452a"
10 = "#90d762"
11 = "#e2e500"
12 = "#00ff87"
13 = "#4e375a"
14 = "#176c73"
15 = "#00381e"
