tags = ["dark"]

[theme.colors]
background = "#100f0f"
foreground = "#cecdc3"
bright-foreground = "#fffcf0"

[theme.colors.palette]
0 = "#100f0f"
1 = "#d14d41"
2 = "#879a39"
3 = "#d0a215"
4 = "#4385be"
5 = "#ce5d97"
6 = "#3aa99f"
7 = "#878580"
8 = "#575653"
9 = "#af3029"
10 = "#66800b"
11 = "#ad8301"
12 = "#205ea6"
13 = "#a02f6f"
14 = "#24837b"
15 = "#cecdc3"
