tags = ["light"]

[theme.colors]
background = "#f8f9fb"
foreground = "#3b4a7a"
bright-foreground = "#414d7c"

[theme.colors.palette]
0 = "#1f2842"
1 = "#985248"
2 = "#577159"
3 = "#be6b00"
4 = "#3a577d"
5 = "#7c5c97"
6 = "#925780"
7 = "#b0b5c5"
8 = "#1f2842"
9 = "#cc4a35"
10 = "#719679"
11 = "#f1a527"
12 = "#6089c0"
13 = "#7d7396"
14 = "#aa869d"
15 = "#d6dbeb"
