tags = ["dark"]

[theme.colors]
background = "#111522"
foreground = "#d6dbeb"
bright-foreground = "#d0d4e2"

[theme.colors.palette]
0 = "#252c47"
1 = "#ea563e"
2 = "#6ead7b"
3 = "#f8b330"
4 = "#596cf7"
5 = "#7c719e"
6 = "#d588c1"
7 = "#dce0ee"
8 = "#38425c"
9 = "#d17264"
10 = "#8c9e8f"
11 = "#eac58c"
12 = "#5186cb"
13 = "#9b7cee"
14 = "#d17ab6"
15 = "#fff6e1"
