tags = ["light"]

[theme.colors]
background = "#ffff54"
foreground = "#000000"
bright-foreground = "#000000"

[theme.colors.palette]
0 = "#000000"
1 = "#ffff54"
2 = "#ffff54"
3 = "#ffff54"
4 = "#000000"
5 = "#ffff54"
6 = "#ffffff"
7 = "#c6c6c6"
8 = "#000000"
9 = "#ffff54"
10 = "#ffff54"
11 = "#ffff54"
12 = "#000000"
13 = "#ffff54"
14 = "#ffffff"
15 = "#c6c6c6"
