tags = ["light"]

[theme.colors]
background = "#ffffff"
foreground = "#000000"
bright-foreground = "#000000"

[theme.colors.palette]
0 = "#000000"
1 = "#a60000"
2 = "#006800"
3 = "#6f5500"
4 = "#0031a9"
5 = "#721045"
6 = "#005e8b"
7 = "#a6a6a6"
8 = "#595959"
9 = "#972500"
10 = "#00663f"
11 = "#884900"
12 = "#3548cf"
13 = "#531ab6"
14 = "#005f5f"
15 = "#595959"
