tags = ["dark"]

[theme.colors]
background = "#000000"
foreground = "#ffffff"
bright-foreground = "#ffffff"

[theme.colors.palette]
0 = "#000000"
1 = "#ff5f59"
2 = "#44bc44"
3 = "#d0bc00"
4 = "#2fafff"
5 = "#feacd0"
6 = "#00d3d0"
7 = "#a6a6a6"
8 = "#595959"
9 = "#ff7f9f"
10 = "#00c06f"
11 = "#fec43f"
12 = "#79a8ff"
13 = "#b6a0ff"
14 = "#6ae4b9"
15 = "#ffffff"
