tags = ["dark"]

[theme.colors]
background = "#21252b"
foreground = "#e6e6e6"
bright-foreground = "#e6e6e6"

[theme.colors.palette]
0 = "#1d1f23"
1 = "#e27881"
2 = "#98c379"
3 = "#eac786"
4 = "#71b9f4"
5 = "#c88bda"
6 = "#62bac6"
7 = "#c9ccd3"
8 = "#4a505a"
9 = "#e68991"
10 = "#a8cc8e"
11 = "#edcf97"
12 = "#8dc7f6"
13 = "#d3a2e2"
14 = "#78c4ce"
15 = "#e6e6e6"
