tags = ["dark"]

[theme.colors]
background = "#0f0f1a"
foreground = "#ededfe"
bright-foreground = "#ffffff"

[theme.colors.palette]
0 = "#0a0a13"
1 = "#ff0063"
2 = "#00f992"
3 = "#ffe900"
4 = "#00a4ff"
5 = "#ff57fd"
6 = "#00ffed"
7 = "#ededff"
8 = "#3e3e4b"
9 = "#ff948b"
10 = "#00fcb9"
11 = "#ffff68"
12 = "#3ea0ff"
13 = "#ff93ff"
14 = "#38ffff"
15 = "#f8f8ff"
