tags = ["light"]

[theme.colors]
background = "#ffffff"
foreground = "#000000"
bright-foreground = "#000000"

[theme.colors.palette]
0 = "#000000"
1 = "#ff0000"
2 = "#59d600"
3 = "#e3be00"
4 = "#00a2ff"
5 = "#c17ecc"
6 = "#00d0d6"
7 = "#c0c4bb"
8 = "#8f928b"
9 = "#ff0013"
10 = "#6dd800"
11 = "#ccbe00"
12 = "#88c9ff"
13 = "#e9a7e1"
14 = "#00d7d9"
15 = "#f6f6f4"
