tags = ["light"]

[theme.colors]
background = "#ff8cd9"
foreground = "#0b0b0b"
bright-foreground = "#000000"

[theme.colors.palette]
0 = "#0c0c0c"
1 = "#a80f20"
2 = "#c7ff98"
3 = "#fff965"
4 = "#145fcd"
5 = "#ffe9ff"
6 = "#9effef"
7 = "#fbf0fa"
8 = "#434343"
9 = "#d91329"
10 = "#d3ffaf"
11 = "#ffef50"
12 = "#0075ea"
13 = "#ffefff"
14 = "#93ffef"
15 = "#fff3fe"
