tags = ["dark"]

[theme.colors]
background = "#241c36"
foreground = "#eef4f6"
bright-foreground = "#eef4f6"

[theme.colors.palette]
0 = "#241c36"
1 = "#ec7979"
2 = "#79ecb3"
3 = "#ece279"
4 = "#a979ec"
5 = "#ec79ec"
6 = "#79ecec"
7 = "#eef4f6"
8 = "#56447a"
9 = "#ef8f8f"
10 = "#9fefbf"
11 = "#efe78f"
12 = "#b78fef"
13 = "#ef8fcf"
14 = "#9fefef"
15 = "#f8fafc"
